theme: jekyll-theme-minimal


permalink: /:year-/:title/

title: Progress 2032
url-pretty: "http://www.Progress32.org"
rss-description: Progress32 Blog RSS

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - README.md
